language: python
python: 3.7

cache: pip

install:
    - pip install -r ./requirements.txt

script:
    - cd ./test
    - python ./base.unittest.py

after_success:
    - bash <(curl -s https://codecov.io/bash)
