language: python
dist: bionic
python: 3.7

install:
    # Install CERN ROOT
    - curl -o root.tar.gz https://root.cern/download/root_v6.18.02.Linux-ubuntu18-x86_64-gcc7.4.tar.gz
    - tar xvf root.tar.gz
    - . ./root/bin/thisroot.sh
    # Install package dependency
    - pip install -r ./requirements.txt
    # For code coverage
    - pip install codecov

script:
    - make test

after_success:
    - codecov

deploy:
    provider: pypi
    user: yipengsun
    skip_cleanup: true
    on:
        tags: true
    password:
        secure: T1dGNmYyeoP/ZQEH5GG66hyo+RsCKgpKh1uF5GbqrHkZK8ouUKIS/YhTHbeZ4hVt5t6gJUinSqCq3iPKeSwx1Nv6jzKPXbZ/6OYFH6DzlAwrmYTwsR3z5SLfhUZ7mtIWKcmX9rzgPjgMuMOOANwHDZ13jQNnxv8KPXqn0u+nE0DTwCkfvWVpbflKvETYCkPED5GPeD538NR+dKqyM+ckqBhK3Fzk/6iaYOs4IUuRH9LRza2QslaDoh3smoJTj1exwGTl34GE1pUSoGWTuradXHRyzIStuUCujKpzhgFv2EP6C1shxe4qpxARPFwJOZfqNEb1XydsVgZ3qi0iEVmazS2KNV6eNEb0D9IFCNaPPSiwy9R0HDO3ikQ9oGNziI9OK74txVHJ/GEudHgeKOZUkC/Qz+wgWCpveQzfiU2CvvRh/WvblwdOYYECrjrmct+KC3QtG4ygFx1UBuLbNx8X7rDGn9ygcdtGcKkNK/8n8wOHFAnxJuu7qGQIZA7JFK+yv/q1yUuUvTY/sJHuXaSM2yjjlS8Hez6WYYv9CYj/HYLb1Wncn+Wh9iCaL2rk73u/1hEY6jaMc6wQpq6rg1bB0HkF9ZMD7515unp2WX7pjCS1tqT6aIW2vtmDoxLIqV5+2aLA6DS5LUcXTkAMIrq+SNlED05MpIR0wTr1ijE6peg=
