language: python
dist: bionic
python: 3.8

install:
    # Install CERN ROOT
    - curl -o root.tar.gz https://root.cern/download/root_v6.18.02.Linux-ubuntu18-x86_64-gcc7.4.tar.gz
    - tar xvf root.tar.gz
    - . ./root/bin/thisroot.sh
    # Install package dependency
    - pip install -r ./requirements.txt
    # For code coverage
    - pip install codecov

script:
    - export PYBABYMAKER_VERSION=$(git describe --tags --abbrev=0)
    - echo 'version = "'"${PYBABYMAKER_VERSION}"'"' >> ./pyBabyMaker/__init__.py
    - make test

after_success:
    - codecov

deploy:
    provider: pypi
    edge: true
    user: yipengsun
    password:
        secure: hBm1jYib+sZhPcKGAOct/jVbXc8GNnvg04oTDTzRJVLPam1F8jI9Nx3398EHqtY0frotYQLmef/8JOW6BOEgzy+u9cfClYRlNtLfpHHA5WvTNR9SHAD+P0F5jj0O0qMaznw/hDp1BfqSTuB4k3Wymr3x9RR4LT1qwnzWnC7/aRKdt2nXYya+STsSJ9JGp5dD238HDnsdjd0q2iaps0aL3b3hotfbjqwAFVftGFMED/5UFWOoOZMr1KVPiBsTIYcn2p8dkWNgWbEHHI0C5qK2BYTsPYnLnfpebiDZYQR4XVQEV+splMH53m7ueOoQu76EpHOySYJsch0GilGxW8n4jYzmySedApvcslzzTBa8KNEjO+47MFBaKEFBoI2WzBxbKF3qM973Xgbvm1mXMa/WvgCAOZCYZc8EJymjrrgjJA2bACnqOIemN9b+80i83SrBbpE1pB8oeWYn1Nfw1K4o8NuJ3i8emySIvCCFH2QJ9g1+ojWn6TL2Qf7XO3fpbuMSaZYEDX3X6sI8uzeug2MjzrPM/sHszUrtv8jm/RNvuwJQ/dG2NY34HFb68CDZrL0X8v2bpzWWhTb4JSGQR44ybb3shyzheam7cXdrvyhT+AL5pYxa/kyiyVydBFf5ZNdaQQEaqseFlq0FS9jYWwbY+G3GU1iGmJVmqEBYP00uNNk=
    on:
        tags: true
