#!/usr/bin/env python3
#
# Author: Yipeng Sun
# License: BSD 2-clause
# Last Change: Thu Sep 02, 2021 at 03:45 PM +0200

import sys

from ROOT import RDataFrame
from numpy import count_nonzero


def cuts_ATuple(ntp_path):
    rdf = RDataFrame('TupleB0/DecayTree', ntp_path)
    return rdf.Filter('Y_PT > 10000').Filter('Y_ISOLATION_BDT > 0').Define(
        'RandStuff', '(D0_P+Y_PT)*3.14'
    ).Define(
        'some_var', 'Y_PT + Y_PZ'
    ).Define(
        'some_other_var', 'some_var*3.14'
    )


if __name__ == '__main__':
    test_brs = ['RandStuff', 'some_other_var']

    df_rdf = cuts_ATuple(sys.argv[1])
    brs_rdf = df_rdf.AsNumpy(columns=test_brs)

    df_bm = RDataFrame('tree', sys.argv[2])
    brs_bm = df_bm.AsNumpy(columns=test_brs)

    ok = True
    for br in test_brs:
        br_rdf = brs_rdf[br]
        br_bm = brs_bm[br]
        br_comp = br_rdf - br_bm

        print('Size of {}: in RDF: {}, in babymaker: {}'.format(
            br, br_rdf.size, br_bm.size))
        ok = ok and (br_rdf.size == br_bm.size)
        ok = ok and not count_nonzero(br_comp)  # 2 arrays are identical
        if ok:
            print('Branch {} is the same'.format(br))

    if ok:
        print('Everything is fine!')
        sys.exit(0)
    else:
        print('The ntuples generated by babymaker is not identical to RDF!')
        sys.exit(255)
